# Generated by Django 4.0.5 on 2022-08-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
